spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kol89

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: none

someParameter:
  value: 5463
